### ISSUE TITLE
Why the event is called `connected`

### ISSUE THREAD

**Issue by dy** [WebReflection/disconnected#5]
Just curious - why that name? Because of `connectedCallback`, `disconnectedCallback`?

That doesn't seem to be standard pattern of naming events though https://developer.mozilla.org/en-US/docs/Web/Events, usually events have Pr. S. or Pr. Cont. form, `connect`, `disconnect`.

Besides, `connected` seems to conflict with [Telephony API](https://developer.mozilla.org/en-US/docs/Web/Events) (weak argument, but still).

**Comment by WebReflection** [comment]
> Because of `connectedCallback`, `disconnectedCallback`?

yes

> That doesn't seem to be standard pattern of naming events though

both events are fired when **the action already happened**, so that preventing the event default would be a no-op.

`DOMContentLoaded` is another super common event name that is triggered when there's no way to prevent it, and it already happened.
